### ISSUE TITLE
Aborted startup and server won't die

### ISSUE THREAD

**Issue by hazmatzo** [carbonfive/spraygun-react#79]
Not sure if this is an issue with this app per se, but I notice that if I start my app (`yarn start`) and it doesn't load for some reason, for instance the wrong version of node on the client side, puma isn't killed and it remains really hard to kill it. Instead of being able to call `pkill` and have it work, I gave up and restarted. Client dev said they did the same thing.

**Comment by mattbrictson** [comment]
I assume this is referring to the `yarn start` script advocated in the spraygun + Rails document here?

https://github.com/carbonfive/spraygun-react/blame/master/docs/how-to-use-with-rails-backend.md#L77

```
"start": "concurrently -k -r npm:start:client npm:start:server
```

The `-k` option is supposed to automatically "kill other processes if one exits or dies" (ref: [usage](https://github.com/kimmobrunfeldt/concurrently#usage)). It sounds like that isn't working. My understanding of this feature is that if e.g. the client process dies, then the service process should be automatically killed.

It could be a bug in `concurrently`, like https://github.com/kimmobrunfeldt/concurrently/issues/155

Otherwise I am not sure... maybe there is a process runner that we should recommend instead if `concurrently` is buggy?

**Comment by mattbrictson** [comment]
These may be alternatives to `concurrently`:

* [npm-run-all](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md)
* [shell-executor](https://github.com/royriojas/shell-executor)

**Comment by hazmatzo** [comment]
Interesting. I'll try to take a look at them when I get a chance. If I'm on the project for longer (and time permitting), I may switch concurrently out and give one of the others a try.

**Comment by mattbrictson** [comment]
This repo is being archived in favor of <https://github.com/carbonfive/spraygun-react-ts>. Closing all open issues.
